# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b65e332f289fdba04711375ea12e5a434f25eff2eadf275dc509199bc9c944970e7ef76d348cc8ebd47d68604b662966da1b737590ba8db549a7d5b780850425

test:
  secret_key_base: 54ff678c44c7a86afe9ae28dc38b58fd0e2702e25b7f5e4a7166a2acdfcb18d06cce95ad16eff477afafc2437b0c182b86b2bbdb65ec2ad10f9eb2d4bc9fcedf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
